---
  - name: Add files and change ownership of files
    hosts: localhost
    tasks:
      - name: Creating files
        file:
          path: /root/test_config1
          state: touch
          mode: u=rw,g=rw,o=r
      - name: Creating files
        file:
          path: /root/test_config2
          state: touch
          mode: u=rw,g=rw,o=r
      - name: Creating files
        file:
          path: /root/test_config3
          state: touch
          mode: u=rw,g=rw,o=r